apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: ${PROMETHEUS_URL} # http://prometheus:9090 locally, localhost on the cloud ops VM
    isDefault: true
